# Generated by Django 4.0.4 on 2022-07-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_provider', models.CharField(max_length=11)),
                ('user_name', models.CharField(max_length=500)),
                ('card_number', models.CharField(max_length=21, unique=True)),
                ('card_cvv', models.CharField(max_length=5)),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
