# Generated by Django 4.0.4 on 2022-07-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('product_title', models.CharField(max_length=255)),
                ('product_subtitle', models.CharField(max_length=255)),
                ('product_description', models.CharField(max_length=1000)),
                ('product_code', models.CharField(max_length=15)),
                ('product_price', models.CharField(max_length=5)),
            ],
        ),
    ]
