# Generated by Django 4.0.4 on 2022-07-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardUser', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=11)),
            ],
        ),
        migrations.DeleteModel(
            name='CardUser',
        ),
    ]
