# Generated by Django 4.0.4 on 2022-08-08 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardUser', '0003_transaction_delete_carduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='product_name',
        ),
    ]
